# Generated by Django 3.1.4 on 2020-12-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RealtimeAPS', '0002_project_userproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('up_lim_1', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('up_lim_2', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('up_lim_3', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('low_lim_1', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('low_lim_2', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('low_lim_3', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='RealtimeAPS.project')),
            ],
        ),
        migrations.CreateModel(
            name='ColorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedtime', models.DateTimeField()),
                ('Red', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Green', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Blue', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='DataManagement.sensor')),
            ],
        ),
    ]
