# Generated by Django 3.1.4 on 2020-12-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorlog',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorlogs', to='DataManagement.sensor'),
        ),
        migrations.CreateModel(
            name='TiltLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedtime', models.DateTimeField()),
                ('temp', models.DecimalField(decimal_places=1, max_digits=10)),
                ('aaxis', models.DecimalField(decimal_places=4, max_digits=10)),
                ('baxis', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiltlogs', to='DataManagement.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedtime', models.DateTimeField()),
                ('tran', models.DecimalField(decimal_places=3, max_digits=10)),
                ('vert', models.DecimalField(decimal_places=3, max_digits=10)),
                ('long', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='DataManagement.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='ACLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedtime', models.DateTimeField()),
                ('cola', models.DecimalField(decimal_places=4, max_digits=20)),
                ('colb', models.DecimalField(decimal_places=4, max_digits=20)),
                ('colc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aclogs', to='DataManagement.sensor')),
            ],
        ),
    ]
