# Generated by Django 3.1.4 on 2021-01-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0002_auto_20201211_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedtime', models.DateTimeField()),
                ('temp', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tplogs', to='DataManagement.sensor')),
            ],
        ),
    ]
